### ISSUE TITLE
 ERROR in ../node_modules/nativescript-escpos-printer/index.ts

### ISSUE THREAD

**Issue by comporell** [growerp/nativescript-escpos-printer#1]
### Make sure to check the demo app(s) for sample usage 
I checked the demo app it is possible to run the demo app. 

### If the demo apps cannot help and there is no issue for your problem, tell us about 
When the app is included in a project via "tns plugin add nativescript-escpos-printer", npm displays an error message.

### Which platform(s) does your issue occur on?
- Android 8.0.0
- device

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.3.0
- Cross-platform modules: 6.3.2
- Runtime(s): 6.3.0

### Please, tell us how to recreate the issue in as much detail as possible. 
Just try to add it to a project via "tns plugin add nativescript-escpos-printer". I receive this message below

> ERROR in ../node_modules/nativescript-escpos-printer/index.ts
> Module build failed (from ../node_modules/@ngtools/webpack/src/index.js):
> Error: G:\angular\Dirt\node_modules\nativescript-escpos-printer\index.ts is missing from the TypeScript compilation. Please ma
> ke sure it is in your tsconfig via the 'files' or 'include' property.
> The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged
>  library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angul
> ar Package Format (https://goo.gl/jB3GVv).
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (G:\angular\Dirt\node_modules\@ngtools\webpack\src\angular_compiler_p
> lugin.js:913:23)
>     at NativeScriptAngularCompilerPlugin.getCompiledFile (G:\angular\Dirt\node_modules\nativescript-dev-webpack\plugins\Native
> ScriptAngularCompilerPlugin.js:28:26)
>     at plugin.done.then (G:\angular\Dirt\node_modules\@ngtools\webpack\src\loader.js:41:31)
>     at process._tickCallback (internal/process/next_tick.js:68:7)
>  @ ./app/shared/print.service.ts 3:0-58 7:31-42 49:20-31
>  @ ./app/app.module.ts
>  @ ./main.ts

**Comment by growerp** [comment]
Hi , thank you for trying this plugin.
not sure why you have this error, because i cannot reproduce it here on Linux.

$tns plugin add nativescript-escpos-printer
+ nativescript-escpos-printer@1.0.0
added 1 package from 1 contributor and audited 17641 packages in 21.177s

21 packages are looking for funding
  run `npm fund` for details

found 5 moderate severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Successfully installed plugin nativescript-escpos-printer.

Another thing you can do is add the following line to package.json in the 'dependencies' section:
    "nativescript-escpos-printer": "^1.0.0",
then run: tns build android/ios 

hope this helps!

**Comment by elgibor-solution** [comment]
Hi, I also got same issue

**Comment by comporell** [comment]
> Hi , thank you for trying this plugin.

Np, thank you for creating it,

> not sure why you have this error, because i cannot reproduce it here on Linux.
> 
> $tns plugin add nativescript-escpos-printer
> 
>     * nativescript-escpos-printer@1.0.0
>       added 1 package from 1 contributor and audited 17641 packages in 21.177s
> 
> 
> 21 packages are looking for funding
> run `npm fund` for details
> 
> found 5 moderate severity vulnerabilities
> run `npm audit fix` to fix them, or `npm audit` for details
> Successfully installed plugin nativescript-escpos-printer.
>
Sorry, my bad for misdirecting you. adding the plugin was smooth. The problem I pasted in the above post occurs when I do "tns run android"
 
> Another thing you can do is add the following line to package.json in the 'dependencies' section:
> "nativescript-escpos-printer": "^1.0.0",
> then run: tns build android/ios
>
> hope this helps!

It is already included in dependencies section.

**Comment by growerp** [comment]
I just released a new version....
please try that and let me know if you still have problems.
Please note, API has changed

**Comment by comporell** [comment]
The new version could be installed now. Thank you for the patch :)

**Comment by bobvann** [comment]
I have the same problem, with last version 2.0.1

**Comment by bobvann** [comment]
I spent few hours trying to make this work and unfortunately I could not.
In my case demo does not work either. Maybe you are using a different version of Nativescript? 

@comporell @growerp what versions are you using?
