### ISSUE TITLE
BT printer

### ISSUE THREAD

**Issue by comporell** [growerp/nativescript-escpos-printer#2]
Hey growerp
I imagine it is possible to use this lib to print a label with BT printer but I could not manage it. Could you give an example how it could be used?
Best Regards,

**Comment by growerp** [comment]
This is meant to be at a restaurant were the printing location like kitchen and bar are further away, where Bluetooth is useless.....there are however a number of bluetooth plugins which only work on BT.
search for 'escpos bluetooth nativescript' and sure you will find some.
regards,
Hans
