### ISSUE TITLE
Can I custom style for string?

### ISSUE THREAD

**Issue by dungfv** [growerp/nativescript-escpos-printer#3]
Thanks for creating this plugin!
My application needs to print out invoice types. My question is is there a way for me to style the input string, or can I print in a scrollView, a txt file?

**Comment by growerp** [comment]
the printing it self is done in https://github.com/growerp/nativescript-escpos-printer/blob/master/demo/app/components/App.vue

the format for styling you you can find at:
https://mike42.me/blog/what-is-escpos-and-how-do-i-use-it

hope this helps?

Regards,
Hans

**Comment by dungfv** [comment]
thanks @growerp! I will try to send a pull request what provide custom styling methods out of the box for this plugin
